<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fingerprint.proto

namespace Fingerprint;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>fingerprint.VerificationResponse</code>
 */
class VerificationResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool match = 1;</code>
     */
    protected $match = false;
    /**
     * Generated from protobuf field <code>string matchedFmd = 2;</code>
     */
    protected $matchedFmd = '';
    /**
     * Generated from protobuf field <code>int32 matchedIndex = 3;</code>
     */
    protected $matchedIndex = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $match
     *     @type string $matchedFmd
     *     @type int $matchedIndex
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Fingerprint::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool match = 1;</code>
     * @return bool
     */
    public function getMatch()
    {

        return $this->match;
    }

    /**
     * Generated from protobuf field <code>bool match = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setMatch($var)
    {
        GPBUtil::checkBool($var);
        $this->match = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string matchedFmd = 2;</code>
     * @return string
     */
    public function getMatchedFmd()
    {
        return $this->matchedFmd;
    }

    /**
     * Generated from protobuf field <code>string matchedFmd = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMatchedFmd($var)
    {
        GPBUtil::checkString($var, True);
        $this->matchedFmd = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 matchedIndex = 3;</code>
     * @return int
     */
    public function getMatchedIndex()
    {
        return $this->matchedIndex;
    }

    /**
     * Generated from protobuf field <code>int32 matchedIndex = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setMatchedIndex($var)
    {
        GPBUtil::checkInt32($var);
        $this->matchedIndex = $var;

        return $this;
    }

}

